#resume_epoch: 26
epochs: 100 #100
batch_size: 8
learning_rate: 0.0001
early_stopping: False
train_dataset_path: 'data/pretraining/train'
val_dataset_path: 'data/pretraining/val'
test_dataset_path: 'data/pretraining/test'
