epochs: 60 #100
batch_size: 4
learning_rate: 0.0001
early_stopping: False
image_size: 128 # At training, random crops of (image_size//2, image_size//2) are used.
num_msrb: 3
num_features: 128
workers: 2
train_dataset_path: 'data/pretraining/train'
val_dataset_path: 'data/pretraining/val'
test_dataset_path: 'data/pretraining/test'
